### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'norm'

### ISSUE THREAD

**Issue by etetteh** [davda54/sam#2]
I am running your implementation in Colab, and everything is working well (though taking a lot of time even with a GPU runtime). However, when I try using sam in my own setup on the same cifar-10 I get the following error 

`Training model...

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<timed exec> in <module>

<ipython-input-12-edbc4519b969> in train(train_loader, model, optimizer, epoch)
     32         loss = smooth_crossentropy(output, target)
     33         loss.mean().backward()
---> 34         optimizer.first_step(zero_grad=True)
     35 
     36         smooth_crossentropy(model(input_), target).mean().backward()

~/anaconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py in decorate_no_grad(*args, **kwargs)
     47         def decorate_no_grad(*args, **kwargs):
     48             with self:
---> 49                 return func(*args, **kwargs)
     50         return decorate_no_grad
     51 

~/Downloads/mila project/udacity_DP_FL/sam/sam.py in first_step(self, zero_grad)
     14     @torch.no_grad()
     15     def first_step(self, zero_grad=False):
---> 16         grad_norm = self._grad_norm()
     17         for group in self.param_groups:
     18             scale = group["rho"] / (grad_norm + 1e-12)

~/Downloads/mila project/udacity_DP_FL/sam/sam.py in _grad_norm(self)
     44                     torch.stack([
     45                         p.grad.norm(p=2)
---> 46                         for group in self.param_groups for p in group["params"]
     47                     ]),
     48                     p=2

~/Downloads/mila project/udacity_DP_FL/sam/sam.py in <listcomp>(.0)
     44                     torch.stack([
     45                         p.grad.norm(p=2)
---> 46                         for group in self.param_groups for p in group["params"]
     47                     ]),
     48                     p=2

AttributeError: 'NoneType' object has no attribute 'norm'`

**Comment by davda54** [comment]
Hi, thank you very much for raising this issue. I've added a NoneType check for the computation of gradient norm. Does it work now for you?

**Comment by etetteh** [comment]
No please.

`<ipython-input-15-a110353a824e> in train(train_loader, model, optimizer, epoch)
     45         with torch.no_grad():
     46             prec1, _ = accuracy(output.data, label, topk=(1, 2))
---> 47             losses.update(loss.item(), img.size(0))
     48             top1.update(prec1.item(), img.size(0))
     49     #         top2.update(prec2.item(), img.size(0))

**ValueError: only one element tensors can be converted to Python scalars**`

**Comment by davda54** [comment]
Could you please send me your code so I can see where's the problem? Thanks :)

**Comment by davda54** [comment]
... solved by email, closing this issue.
