### ISSUE TITLE
The value of rho

### ISSUE THREAD

**Issue by guozhiyao** [davda54/sam#20]
Hi,
    Thank you for your implement.
    I have a question about rho. Should the value of rho be adjusted according to lr? If the rho is much larger than lr, perhaps it will cause the model to fail to converge. And if I use the lr scheduler to adjust lr, should rho to be adjusted?

**Comment by davda54** [comment]
Hi, I think that the value of `rho` depends on the loss landscape and not on learning rate. But of course, you should try it, the reality does not care about my beliefs :)

**Comment by guozhiyao** [comment]
Thanks a lot for your reply.
