### ISSUE TITLE
argument values to pass to train.py

### ISSUE THREAD

**Issue by le000043** [davda54/sam#24]
Thanks for implementing this!
what are the argument values passed to train.py in order to train Wide Resnet without SAM or ASAM?
Thanks

**Comment by davda54** [comment]
There's no such option, the code just shows a simple usage of (A)SAM.

If you want to replicate the results in README, just set:
```python
optimizer = torch.optim.SGD(model.parameters(), lr=args.learning_rate, momentum=args.momentum, weight_decay=args.weight_decay)
```

and then do the standard forward-backward pass, nothing unusual:
```python
predictions = model(inputs)
loss = smooth_crossentropy(predictions, targets)
loss.mean().backward()
optimizer.step()
optimizer.zero_grad()
```
