### ISSUE TITLE
Can SAM be used for GAN training?

### ISSUE THREAD

**Issue by yueruchen** [davda54/sam#27]
Hi,

Thanks for sharing this good repo. I'm wondering that whether it is suitable to combine SAM with GAN training, like WGAN-GP loss? Normally WGAN-GP needs to compute gradient penalty, I'm not sure if this conflicts with SAM. Do you have any idea? Thanks!

**Comment by davda54** [comment]
Hi, I'm really sorry but I haven't tried SAM on GANs. That being said, I'm also very curious about combining GAN training with SAM, so I'm leaving this issue open. Hopefully someone will share their experience :)
