### ISSUE TITLE
Question: Why step_lr?

### ISSUE THREAD

**Issue by JeanKaddour** [davda54/sam#35]
Thank you for the great implementation!

Out of curiosity, why have you added your own `step_lr` scheduler and are not using the cosine annealing scheduler as suggested in the original paper?

**Comment by davda54** [comment]
It is just a simple example :) I've used my old implementation of WRN, which uses the `step_lr` scheduler from the original WRN paper. There's certainly a lot of room for improvement if you want to have a better classifier.

**Comment by JeanKaddour** [comment]
Got it. Thank you!
