### ISSUE TITLE
Question about Cutout

### ISSUE THREAD

**Issue by Mu-Y** [davda54/sam#4]
Hello,

Thanks for the nice implementation! I have a question about the Cutout augmentation in the code below.

```
class Cutout:
    def __init__(self, size=16, p=0.5):
        self.size = size
        self.half_size = size // 2
        self.p = p

    def __call__(self, image):
        if torch.rand([1]).item() > self.p: return image

        left = torch.randint(-self.half_size, image.shape[0] - self.half_size, [1]).item()
        top = torch.randint(-self.half_size, image.shape[1] - self.half_size, [1]).item()
        right = min(image.shape[0], left + self.size)
        bottom = min(image.shape[1], top + self.size)

        image[max(0,left):right, max(0,top):bottom, :] = 0
        return image
```

It seems like here you are assuming that the shape of `image` is `[Height, Width, Channel]`, but actually here the input `image` is in `[Channel, Height, Width]`. I think the Cutout function need to be modified so that it assumes `image` to be the shape as `[Channel, Height, Width]`. Is my understanding correct here, or maybe I'm missing anything? Thanks!

**Comment by davda54** [comment]
Oh wow, you're absolutely right, thank you very much! :)
