### ISSUE TITLE
Experiments on object detection task

### ISSUE THREAD

**Issue by shuo-ouyang** [davda54/sam#41]
Hi, is there anyone who applied SAM on the COCO object detection dataset? How do we set the hyper-parameter rho? I have tested rho=0.05 but got a performance degradation compared with SGD.

**Comment by ravich3373** [comment]
@shuo-ouyang did you try SAM on object detection task? Can you please share your experience here?

**Comment by shuo-ouyang** [comment]
@ravich3373 I have tried it on the object detection task. In my experiments, SAM with rho=0.05 does not improve ap and ap on the coco detection task, and only improves ap with a smaller rho (0.01).

**Comment by ravich3373** [comment]
thanks for the info.

**Comment by ravich3373** [comment]
@shuo-ouyang did you observe any speedup in convergence? or better generalization? Thanks.
