### ISSUE TITLE
How do we give credit?

### ISSUE THREAD

**Issue by ClashLuke** [davda54/sam#43]
We're interested in integrating SAM into [HomebrewNLP](https://github.com/HomebrewNLP/HomebrewNLP), and straight-up copying the code without copyright or notice doesn't sit right with me.\
How would you prefer us to cite you?\
I propose adding a header to sam.py as it's done in [Shampoo](https://github.com/google-research/google-research/blob/master/scalable_shampoo/jax/shampoo.py#L1-L34).

**Comment by ClashLuke** [comment]
Until this is resolved, I will add `sam.py` with a default notice to our repository.

**Comment by davda54** [comment]
Hi, thank you very much for using this implementation! :) Adding a header with a link to this repository is absolutely fine, thanks :)
