### ISSUE TITLE
how to train my own data?

### ISSUE THREAD

**Issue by Chenhait** [davda54/sam#53]
thank you!

**Comment by davda54** [comment]
Hi, can you be more specific? You need to provide your own [DataLoader](https://pytorch.org/docs/stable/data.html?highlight=dataloader#torch.utils.data.DataLoader) in order to train on a different dataset.

**Comment by Chenhait** [comment]
> Hi, can you be more specific? You need to provide your own [DataLoader](https://pytorch.org/docs/stable/data.html?highlight=dataloader#torch.utils.data.DataLoader) in order to train on a different dataset.

thank you so so much for your reply!!! I want to use this method to train The Street View House Numbers (SVHN) Dataset. it will be so appreciate if you offer some suggests, since I used to study math, and not very familiar with pytorch. thank you again!
