### ISSUE TITLE
Support for multi devices training

### ISSUE THREAD

**Issue by PForet** [davda54/sam#6]
Hi

Thank you for your great Pytorch implementation! I'm wondering if there is a plan to support multi devices training (with data parallelism). As you might know, SAM benefits a lot from computing a different epsilon for each replica (section 4.1 of the paper on the m-sharpness), and the best generalization is often obtained when training on multiple GPUs or TPUs. It would be an awesome addition to this codebase.

**Comment by prabhtajsingh-bhasin** [comment]
Was trying to get it working on Multiple TPUs using PyTorch XLA. 
Getting this error:
 File "/work/sam.py", line 53, in _grad_norm
    for group in self.param_groups for p in group["params"]
RuntimeError: stack expects a non-empty TensorList
@davda54 can we expect this feature anytime soon?
