### ISSUE TITLE
Multi-network, multi-loss function using SAM

### ISSUE THREAD

**Issue by zhanglina94** [davda54/sam#63]
Hi, how should I use SAM if I use multiple networks and multiple loss functions? Is there a sample project? There is only one network and one loss function in this project. Looking forward to your answer. Thanks!

**Comment by davda54** [comment]
Hi, there is no sample project for this functionality. What is the problem when you implement multi-task learning with SAM, could you be more specific?

**Comment by zhanglina94** [comment]
I did finish my work

Thank you very much！



发自Naver邮箱应用软件
-----Original Message-----
From: "David ***@***.***>
To: ***@***.***>
CC: ***@***.***>, ***@***.***>
Sent: 2022. 5. 19 下午 10:02:33
Subject: Re: [davda54/sam] Multi-network, multi-loss function using SAM (Issue #63)

Hi, there is no sample project for this functionality. What is the problem when you implement multi-task learning with SAM, could you be more specific?
