### ISSUE TITLE
Any plans to implement the paper "Sharpness-Aware Training for Free"?

### ISSUE THREAD

**Issue by waitingcheung** [davda54/sam#69]
The computational overhead of SAM is a large obstacle to adapt it. This [paper](https://arxiv.org/abs/2205.14083) proposes to perform sharpness-aware training with no additional cost while maintaining the generalization performance of SAM.

The official implementation is currently not publicly available. A public implementation will definitely help the community.

**Comment by rtxbae** [comment]
Would love this too since current (A)SAM doubled the computational cost.

**Comment by davda54** [comment]
Hi, thanks for creating this issue, I wasn't aware of the paper :) It would be difficult to incorporate that idea into this repository -- it is not really an optimizer but an auxiliary loss AFAIK. I would like to keep the code as minimal as possible. I'm planning to add the GSAM variant though: [https://github.com/davda54/sam/pull/72](https://github.com/davda54/sam/pull/72)
