### ISSUE TITLE
i found it hard to implement this optimizer on yolov5.looking forward to s.b. could do me a FAVOR. THX

### ISSUE THREAD

**Issue by EveningLin** [davda54/sam#77]

**Comment by EveningLin** [comment]
![q](https://user-images.githubusercontent.com/110521494/186228444-114356cb-b321-4646-97a4-c0ae155bfa64.png)

**Comment by EveningLin** [comment]
nan really confuse me

**Comment by CharlesGong12** [comment]
hey, you can check here https://github.com/davda54/sam/issues/7
