### ISSUE TITLE
Using SAM with torch.cuda.amp.GradScaler

### ISSUE THREAD

**Issue by yossigandelsman** [davda54/sam#79]
Hi, 
Thanks for the pytorch implementation of SAM!

I am trying to replace an optimizer with SAM, in a code that uses automatic mixed precision (specifically - something very close to this one: https://github.com/facebookresearch/mae/blob/main/engine_finetune.py#L66), and I am not sure how should I incorporate the different steps in this process. Did anyone try to do something like that already?

Thank you for your answer!

**Comment by ancestor-mithril** [comment]
Any news on this?
