### ISSUE TITLE
About SGD parameters

### ISSUE THREAD

**Issue by bobo0810** [davda54/sam#9]
Hi @davda54 
Thank you for your great Pytorch implementation!

I want to know whether the momentum of SGD can be safely removed when using the SAM optimizer? That is, is momentum necessary for the SAM optimizer? Because momentum has a negative impact on my task.
  ```python
base_optimizer = torch.optim.SGD
optimizer = SAM(base_optimizer, rho=0.05, lr=0.1, weight_decay=0.0005,momentum=0)
  ```

Thank you again and look forward to replying~

**Comment by davda54** [comment]
Hi! 

Yes, you can safely remove the momentum -- it influences only the `base_optimizer`, which can be arbitrary.

PS: don't forget to put the model parameters into the `init` method (if you use an unmodified implementation of SAM):
```python
optimizer = SAM(model.parameters(), base_optimizer, rho=0.05, lr=0.1, weight_decay=0.0005, momentum=0)
```

**Comment by bobo0810** [comment]
> Hi!
> 
> Yes, you can safely remove the momentum -- it influences only the `base_optimizer`, which can be arbitrary.
> 
> PS: don't forget to put the model parameters into the `init` method (if you use an unmodified implementation of SAM):
> 
> ```python
> optimizer = SAM(model.parameters(), base_optimizer, rho=0.05, lr=0.1, weight_decay=0.0005, momentum=0)
> ```

Thank you, wish you a happy life！
